# Generated by Django 4.2.4 on 2023-10-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_cell_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_of_document',
            field=models.CharField(max_length=15),
        ),
    ]
