# Generated by Django 4.2.4 on 2023-09-02 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_of_property",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartamento"),
                            ("house", "Casa"),
                            ("room", "Habitación"),
                            ("office", "Oficina"),
                            ("studio", "Aparta-Estudio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_for_rent",
                    models.PositiveIntegerField(help_text="Time for rent in months"),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "size",
                    models.PositiveIntegerField(help_text="Size in square meters"),
                ),
                ("rental_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability", models.BooleanField(default=True)),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/property/property_images/",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updateded_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropertyRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="property.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="property.property",
                    ),
                ),
            ],
        ),
    ]
