# Generated by Django 4.2.4 on 2023-11-04 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "type_of_property",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartamento"),
                            ("house", "Casa"),
                            ("room", "Habitación"),
                            ("office", "Oficina"),
                            ("studio", "Aparta-Estudio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "time_for_rent",
                    models.CharField(
                        choices=[
                            ("1", "1 mes"),
                            ("3", "3 meses"),
                            ("6", "6 meses"),
                            ("12", "1 año"),
                            ("24", "2 años"),
                            ("36", "3 años"),
                        ],
                        help_text="Tiempo de renta en meses",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                (
                    "size",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tamaño en metros cuadrados (m²)",
                        max_digits=10,
                    ),
                ),
                (
                    "rental_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio de Alquiler (COP)",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rented", "Alquilado"),
                            ("available", "Disponible"),
                            ("pending", "Pendiente"),
                            ("other", "Otro"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="property.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/property/property_images/",
                    ),
                ),
                (
                    "is_main_image",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="¿Es la imagen principal de tu propiedad?",
                        null=True,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="property.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_bedrooms",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "num_bathrooms",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=10,
                    ),
                ),
                ("parking_spaces", models.PositiveIntegerField()),
                ("garden", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                ("backyard", models.BooleanField(default=False)),
                ("furnished", models.BooleanField(default=False)),
                (
                    "property",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="property.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="property.property",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
