# Generated by Django 4.2.4 on 2023-09-07 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="updateded_date",
            new_name="updated_date",
        ),
        migrations.CreateModel(
            name="PropertyFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_bedrooms", models.PositiveIntegerField()),
                ("num_bathrooms", models.PositiveIntegerField()),
                ("parking_spaces", models.PositiveIntegerField()),
                ("garden", models.BooleanField(default=False)),
                ("pool", models.BooleanField(default=False)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="property.property",
                    ),
                ),
            ],
        ),
    ]
