# Generated by Django 4.2.4 on 2023-10-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="images",
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media/property/property_images/",
                    ),
                ),
                (
                    "is_main_image",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="¿Es la imagen principal de tu propiedad?",
                        null=True,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="property.property",
                    ),
                ),
            ],
        ),
    ]
