# Generated by Django 4.2.4 on 2023-09-07 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_rename_updateded_date_property_updated_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyfeature",
            name="property",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="property.property",
            ),
        ),
    ]
