# Generated by Django 4.2.4 on 2023-09-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_alter_propertyfeature_property"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyfeature",
            name="backyard",
            field=models.BooleanField(default=False),
        ),
    ]
